#Helles Theme
# [theme]
# primaryColor="#FF4B4B"
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#F0F2F6"
# textColor="#31333F"
# font="sans serif"

# Dunkles Theme:
[theme]
base="dark"
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"